sudo: required

language: c

compiler: gcc

before_install:
    - sudo apt-get -qq update

install:
    - sudo apt-get install -y libjson0 libjson0-dev
    - sudo ./json-c.sh

before_script:
    - cd build
    - cmake ..

script:
    - make -j4

after_script:
    - ./bin/p2p-dedup -v

notifications:
    email:
        - jwhu1024@gmail.com
    
    on_success: change
    on_failure: always
